services:
  traccar:
    image: traccar/traccar:latest
    container_name: traccar
    restart: always
    ports:
      - "8082:8082"   # Web UI
      - "5000-5150:5000-5150/udp" # GPS tracker ports
    volumes:
      - ./logs:/opt/traccar/logs
      - ./data:/opt/traccar/data
      - ./conf:/opt/traccar/conf
